I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_lesson_three.rpy", line 129, in script
    show screen lesson_three_ls8_fills
  File "renpy/common/000statements.rpy", line 646, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen lesson_three_ls8_fills is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_lesson_three.rpy", line 129, in script
    show screen lesson_three_ls8_fills
  File "D:\installedApps\Ren'py\renpy-8.1.3-sdk\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "D:\installedApps\Ren'py\renpy-8.1.3-sdk\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\installedApps\Ren'py\renpy-8.1.3-sdk\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 646, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "D:\installedApps\Ren'py\renpy-8.1.3-sdk\renpy\display\screen.py", line 1220, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen lesson_three_ls8_fills is not known.


Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
HTML Lesson 1.0
Fri Dec 22 03:46:25 2023
